# Generated by Django 5.2 on 2025-04-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_contact_alter_coustomer_details_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
