# Generated by Django 5.2 on 2025-04-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer_details',
            name='category',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], max_length=20),
        ),
    ]
