# Generated by Django 5.2 on 2025-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_coustomer_details_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer_details',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('HOME', 'Home')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PIANO', 'Piano'), ('E_GUITER', 'E_Guiter'), ('A_GUITER', 'A_Guiter'), ('KEY_BOARD', 'Key_Board'), ('FLUTE', 'FLUTE'), ('VIOLIN', 'Violin'), ('DRUMS', 'Drums'), ('TRUMPETS', 'TRUMPETS'), ('PADS', 'Pads'), ('SAXOPHONE', 'Saxophone'), ('SITAR', 'Sitar')], max_length=20),
        ),
    ]
